import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { 
  Download, Share2, Map as MapIcon, Train, Plane, 
  Wallet, Coffee, Sun, Clock, Bookmark, Heart,
  Compass, Sparkles, FileText, Users, TrendingUp, Globe
} from 'lucide-react';

import { jsPDF } from 'jspdf';
import { useAuth } from '../context/AuthContext';
import axios from 'axios';
import ChatAssistant from '../components/ChatAssistant';
import MapComponent from '../components/MapComponent';

export default function TripDetails() {
  const [data, setData] = useState(null);
  const [activeTab, setActiveTab] = useState("itinerary");
  const [mapDay, setMapDay] = useState(null);
  const { user, token } = useAuth();
  const navigate = useNavigate();

  useEffect(() => {
    const saved = sessionStorage.getItem('currentPlan');
    if (saved) {
      setData(JSON.parse(saved));
    } else {
      navigate('/plan');
    }
  }, [navigate]);

  const plan = data?.plan;
  const form = data?.form;

  const downloadPDF = () => {
    const doc = new jsPDF();
    doc.setFont("helvetica", "bold");
    doc.text(`TripGenie Plan to ${form.destination}`, 10, 20);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    let y = 30;
    doc.text(plan.destination_info || "Trip Plan generated by AI", 10, y); y += 10;
    plan.itinerary?.forEach(day => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(`Day ${day.day}: ${day.title}`, 10, y); y += 10;
      day.activities?.forEach(act => {
        if (y > 270) { doc.addPage(); y = 20; }
        doc.text(`- ${act.time_slot}: ${act.place} (${act.estimated_cost})`, 15, y); y += 7;
      });
      y += 5;
    });
    doc.save(`${form.destination}_Trip.pdf`);
  };

  const downloadTXT = () => {
    let content = `TripGenie Plan to ${form.destination}\n\n`;
    content += `${plan.destination_info}\n\n`;
    plan.itinerary?.forEach(day => {
      content += `Day ${day.day}: ${day.title}\n`;
      day.activities?.forEach(act => {
        content += `- ${act.time_slot}: ${act.place} (Est: ${act.estimated_cost})\n  ${act.description}\n`;
      });
      content += `\n`;
    });
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${form.destination}_Trip.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const saveTripToDB = async () => {
    if (!user) {
      alert("Please login to save trips.");
      navigate('/login');
      return;
    }
    try {
      await axios.post("http://127.0.0.1:5000/trips/save", {
        destination: form.destination,
        plan: plan,
        form_details: form
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      alert("Trip saved successfully!");
    } catch (e) {
      alert("Error saving trip: " + e.message);
    }
  };

  if (!data) return null;

  return (
    <div className="max-w-6xl mx-auto px-6 py-12 pb-32">
      {/* Header Image */}
      {plan.image_url && (
        <div className="w-full h-[40vh] rounded-3xl overflow-hidden mb-12 relative shadow-2xl shadow-accent/20">
          <img src={plan.image_url} alt={form.destination} className="w-full h-full object-cover" />
          <div className="absolute inset-0 bg-gradient-to-t from-bg-color via-bg-color/50 to-transparent"></div>
        </div>
      )}
      
      {/* Header Content */}
      <div className={`flex flex-col md:flex-row justify-between items-start gap-8 mb-12 ${plan.image_url ? '-mt-[8vh] md:-mt-[10vh] relative z-10' : ''}`}>
        <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} className="w-full md:w-auto">
          <div className="flex items-center gap-3 text-accent mb-2">
            <MapIcon className="w-5 h-5" />
            <span className="font-medium drop-shadow-md">AI Generated Itinerary</span>
          </div>
          <h1 className="text-3xl md:text-5xl font-bold mb-4 drop-shadow-md">{form.destination}</h1>
          <p className="text-gray-300 text-base md:text-lg max-w-2xl drop-shadow-md">{plan.destination_info}</p>
        </motion.div>
        
        <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} className="grid grid-cols-2 sm:flex gap-3 w-full md:w-auto">
          <button onClick={saveTripToDB} className="glass-btn gap-2 px-6 justify-center sm:w-auto">
            <Heart className="w-4 h-4 text-pink-400" /> <span className="sm:inline">Save</span>
          </button>
          <div className="flex gap-2">
            <button onClick={downloadTXT} className="glass-btn flex-1 sm:px-4 text-accent" title="Download TXT">
              <FileText className="w-4 h-4" />
            </button>
            <button onClick={downloadPDF} className="glass-btn flex-1 sm:px-4 text-accent-purple" title="Download PDF">
              <Download className="w-4 h-4" />
            </button>
            <button onClick={async () => {
              try {
                await axios.post("http://127.0.0.1:5000/community/share", {
                  user_id: user?._id,
                  user_name: user?.name,
                  destination: form.destination,
                  plan: plan,
                  image: plan.image_url
                });
                alert("Shared to community!");
              } catch (e) {
                alert("Failed to share trip.");
              }
            }} className="glass-btn flex-1 sm:px-4 text-accent" title="Post to Community">
              <Users className="w-4 h-4" />
            </button>
            <button className="glass-btn flex-1 sm:px-4">
              <Share2 className="w-4 h-4" />
            </button>
          </div>
        </motion.div>
      </div>

      {/* Quick Stats */}
      <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-12">
        <StatCard icon={<Wallet />} label="Est. Total" value={plan.budget_breakdown?.total_estimated || "N/A"} />
        <StatCard icon={<Plane />} label="Primary Travel" value={plan.travel_plan?.flight?.cost_duration ? "Flight" : plan.travel_plan?.train?.cost_duration ? "Train" : "Bus"} />
        <StatCard icon={<Coffee />} label="Stay Vibe" value={plan.stay_plan?.best_area_to_stay?.split(' ')[0] || "Central"} />
        <StatCard icon={<Sun />} label="Travel Vibe" value={form.travelType} />
        {plan.weather ? (
          <StatCard icon={<Sun />} label="Weather" value={`${plan.weather.temperature}°C`} />
        ) : (
          <StatCard icon={<Sun />} label="Weather" value="N/A" />
        )}
      </div>

      {/* Tabs & Content */}
      <div className="grid lg:grid-cols-3 gap-10">
        <div className="lg:col-span-2 space-y-8">
          <div className="flex gap-8 border-b border-white/10 mb-6 overflow-x-auto">
            {["itinerary", "map", "stay", "travel", "food", "tips"].map(t => (
              <button
                key={t}
                onClick={() => setActiveTab(t)}
                className={`pb-4 text-sm font-bold capitalize transition-all relative ${activeTab === t ? 'text-accent' : 'text-gray-500 hover:text-gray-300'}`}
              >
                {t}
                {activeTab === t && (
                  <motion.div layoutId="activeTab" className="absolute bottom-0 left-0 right-0 h-0.5 bg-accent" />
                )}
              </button>
            ))}
          </div>

          {activeTab === "itinerary" && (
            <div className="space-y-6">
              {Array.isArray(plan.itinerary) ? plan.itinerary.map((day, idx) => (
                <motion.div 
                  key={idx}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: idx * 0.1 }}
                  className="glass-panel p-6 sm:p-8 relative overflow-hidden"
                >
                  <div className="flex items-center gap-4 mb-8">
                    <div className="w-12 h-12 rounded-2xl bg-accent/10 flex items-center justify-center text-accent font-bold text-xl">
                      {day.day}
                    </div>
                    <h3 className="text-2xl font-bold">{day.title}</h3>
                  </div>
                  
                  <div className="space-y-10 relative ml-2 sm:ml-6 border-l border-white/10 pl-6 sm:pl-10">
                    {Array.isArray(day.activities) ? day.activities.map((act, i) => {
                      const isMeal = act.activity_type === 'meal';
                      return (
                        <div key={i} className={`relative p-4 sm:p-5 rounded-2xl transition-all ${isMeal ? 'bg-orange-500/5 border border-orange-500/10' : 'bg-transparent group hover:bg-white/5 border border-transparent hover:border-white/10'}`}>
                          <div className={`absolute -left-[31px] sm:-left-[45px] top-6 w-2.5 h-2.5 rounded-full ring-4 ring-bg-color ${isMeal ? 'bg-orange-400' : 'bg-accent'}`} />
                          <div className="flex flex-col md:flex-row gap-6">
                            <div className="flex-1">
                              <div className="flex flex-col md:flex-row md:items-center justify-between gap-2 mb-2">
                                <div className={`flex items-center gap-2 font-bold ${isMeal ? 'text-orange-400' : 'text-accent-purple'}`}>
                                  {isMeal ? <Coffee className="w-4 h-4" /> : <Clock className="w-4 h-4" />} 
                                  {act.time_slot}
                                </div>
                                <span className="text-xs font-bold px-2 py-1 bg-white/5 rounded-md text-gray-400">
                                  Est: {act.estimated_cost}
                                </span>
                              </div>
                              <h4 className={`text-lg font-bold mb-2 ${isMeal ? 'text-orange-100' : 'text-white'}`}>{act.place}</h4>
                              <p className="text-gray-400 leading-relaxed mb-3">{act.description}</p>
                              <div className="flex flex-wrap gap-3">
                                {act.travel_time && (
                                  <div className="text-xs text-accent bg-accent/5 inline-flex items-center gap-2 px-3 py-1 rounded-lg border border-accent/10">
                                    <Compass className="w-3 h-3" /> {act.travel_time}
                                  </div>
                                )}
                              </div>
                            </div>
                            {act.image_url && act.image_url !== "Leave empty, backend will fetch" && (
                              <div className="w-full md:w-48 h-32 md:h-full min-h-[128px] rounded-xl overflow-hidden shrink-0 shadow-lg shadow-black/20 mt-4 md:mt-0">
                                <img src={act.image_url} alt={act.place} className="w-full h-full object-cover hover:scale-110 transition-transform duration-500" />
                              </div>
                            )}
                          </div>
                        </div>
                      );
                    }) : null}
                  </div>
                </motion.div>
              )) : (
                <div className="glass-panel p-12 text-center">
                  <p className="text-gray-400">Itinerary data is not available in the expected format.</p>
                </div>
              )}
            </div>
          )}

          {activeTab === "map" && (
            <motion.div 
              initial={{ opacity: 0, scale: 0.98 }}
              animate={{ opacity: 1, scale: 1 }}
              className="space-y-6"
            >
              <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-2">
                <div>
                  <h3 className="text-xl font-bold">Interactive Route Map</h3>
                  <p className="text-xs text-gray-400">Visualize your path and discover nearby spots.</p>
                </div>
                <div className="flex gap-2 bg-white/5 p-1 rounded-xl border border-white/10 overflow-x-auto w-full md:w-auto">
                  <button 
                    onClick={() => setMapDay(null)}
                    className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all whitespace-nowrap ${mapDay === null ? 'bg-accent text-white' : 'text-gray-400 hover:text-white'}`}
                  >
                    All Days
                  </button>
                  {plan.itinerary.map(d => (
                    <button 
                      key={d.day}
                      onClick={() => setMapDay(d.day)}
                      className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all whitespace-nowrap ${mapDay === d.day ? 'bg-accent text-white' : 'text-gray-400 hover:text-white'}`}
                    >
                      Day {d.day}
                    </button>
                  ))}
                </div>
              </div>

              <div className="relative group">
                <MapComponent itinerary={plan.itinerary} destinationCoords={plan.destination_coords} selectedDay={mapDay} />
                
                {/* Agentic Tools Floating Panel */}
                <div className="absolute bottom-6 left-6 z-[500] pointer-events-none group-hover:pointer-events-auto">
                  <div className="glass-panel p-4 bg-black/60 border-accent/20 translate-y-4 opacity-0 group-hover:translate-y-0 group-hover:opacity-100 transition-all duration-300">
                    <p className="text-[10px] font-bold text-accent uppercase tracking-widest mb-3">AI Planning Tools</p>
                    <div className="flex flex-col gap-2">
                      <button 
                        onClick={() => {
                          alert("AI is re-optimizing your route to minimize travel time...");
                          // Logic for optimization would go here
                        }}
                        className="flex items-center gap-2 text-xs font-bold hover:text-accent transition-colors"
                      >
                        <Sparkles className="w-3 h-3" /> Optimize Distance
                      </button>
                      <button className="flex items-center gap-2 text-xs font-bold hover:text-accent transition-colors">
                        <TrendingUp className="w-3 h-3" /> Crowd Prediction
                      </button>
                    </div>
                  </div>
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-6 mt-6">
                <div className="glass-panel p-6">
                  <h4 className="font-bold mb-4 flex items-center gap-2 text-accent">
                    <Compass className="w-4 h-4" /> Smart Route Optimization
                  </h4>
                  <p className="text-sm text-gray-400 leading-relaxed">
                    Our Agentic AI has grouped {mapDay ? `Day ${mapDay}` : "all"} attractions based on proximity to reduce your total transit time by an estimated 15%.
                  </p>
                </div>
                <div className="glass-panel p-6">
                  <h4 className="font-bold mb-4 flex items-center gap-2 text-accent-purple">
                    <Globe className="w-4 h-4" /> Real-Time Sync
                  </h4>
                  <p className="text-sm text-gray-400 leading-relaxed">
                    Map markers are synced with live location data. Click any marker to push directions directly to your phone.
                  </p>
                </div>
              </div>
            </motion.div>
          )}

          {activeTab === "stay" && (
            <div className="space-y-6">
              <div className="glass-panel p-8">
                <h3 className="text-2xl font-bold mb-4">Recommended Area</h3>
                <p className="text-gray-300 text-lg flex items-center gap-2">
                   <MapIcon className="w-5 h-5 text-accent" /> {plan.stay_plan?.best_area_to_stay}
                </p>
              </div>
              <div className="grid md:grid-cols-3 gap-6">
                {[
                  { key: 'budget_hostel', label: 'Budget Hostel', color: 'text-green-400' },
                  { key: 'mid_range_hotel', label: 'Mid-range Hotel', color: 'text-accent' },
                  { key: 'luxury_hotel', label: 'Luxury Hotel', color: 'text-accent-purple' }
                ].map(item => (
                  <motion.div key={item.key} className="glass-panel p-6 flex flex-col justify-between">
                    <div>
                      <h4 className={`text-xl font-bold mb-2 ${item.color}`}>{item.label}</h4>
                      <p className="text-lg font-bold mb-1">{plan.stay_plan?.[item.key]?.name}</p>
                      <p className="text-accent font-bold mb-4">{plan.stay_plan?.[item.key]?.price_range}</p>
                      <p className="text-xs text-gray-500 uppercase tracking-widest font-bold mb-2">Booking Hint</p>
                      <p className="text-sm text-gray-400 italic mb-4">{plan.stay_plan?.[item.key]?.booking_hint}</p>
                    </div>
                    <a 
                      href={`https://www.booking.com/searchresults.html?ss=${encodeURIComponent(plan.stay_plan?.[item.key]?.name + ' ' + form?.destination)}`}
                      target="_blank" rel="noopener noreferrer"
                      className="w-full text-center glass-btn py-2 text-xs mb-2"
                    >
                      🏨 Booking.com
                    </a>
                    <a 
                      href={`https://www.makemytrip.com/hotels/${encodeURIComponent(form?.destination?.toLowerCase())}-hotels.html`}
                      target="_blank" rel="noopener noreferrer"
                      className="w-full text-center glass-btn py-2 text-xs"
                    >
                      🏨 MakeMyTrip
                    </a>
                  </motion.div>
                ))}
              </div>
            </div>
          )}

          {activeTab === "travel" && (
            <div className="glass-panel p-8">
              <h3 className="text-2xl font-bold mb-8">Travel Logistics</h3>
              <div className="grid md:grid-cols-2 lg:grid-cols-2 gap-6">
                {Object.entries(plan.travel_plan || {}).map(([mode, details]) => {
                  if (!details.available) return (
                    <div key={mode} className="p-6 rounded-2xl bg-white/5 border border-white/10 opacity-50">
                       <div className="flex items-center gap-3 mb-4">
                        <div className="w-10 h-10 rounded-xl bg-gray-500/10 flex items-center justify-center text-gray-500">
                          {mode === 'flight' ? <Plane className="w-5 h-5" /> : mode === 'train' ? <Train className="w-5 h-5" /> : <Compass className="w-5 h-5" />}
                        </div>
                        <span className="capitalize font-bold text-lg">{mode}</span>
                      </div>
                      <p className="text-sm text-gray-400 italic">No direct {mode} available for this route.</p>
                    </div>
                  );

                  return (
                    <div key={mode} className="p-6 rounded-2xl bg-white/5 border border-white/10 hover:border-accent/30 transition-colors">
                      <div className="flex items-center justify-between mb-4">
                        <div className="flex items-center gap-3">
                          <div className="w-10 h-10 rounded-xl bg-accent/10 flex items-center justify-center text-accent">
                            {mode === 'flight' ? <Plane className="w-5 h-5" /> : mode === 'train' ? <Train className="w-5 h-5" /> : mode === 'bus' ? <Sun className="w-5 h-5" /> : <Compass className="w-5 h-5" />}
                          </div>
                          <span className="capitalize font-bold text-lg">{mode}</span>
                        </div>
                        <div className="text-right">
                          <p className="text-xl font-bold text-white">{details.cost}</p>
                          <p className="text-xs text-accent font-bold uppercase">{details.duration}</p>
                        </div>
                      </div>

                      <div className="space-y-3 mb-6">
                        <div className="flex justify-between text-sm">
                          <span className="text-gray-500">Route</span>
                          <span className="text-gray-300 font-medium">{details.route}</span>
                        </div>
                        
                        {mode === 'flight' && (
                          <>
                            <div className="flex justify-between text-sm">
                              <span className="text-gray-500">Airline</span>
                              <span className="text-gray-300 font-medium">{details.airline}</span>
                            </div>
                            <div className="flex justify-between text-sm">
                              <span className="text-gray-500">Timing</span>
                              <span className="text-gray-300 font-medium">{details.departure_arrival}</span>
                            </div>
                          </>
                        )}

                        {mode === 'train' && (
                          <>
                            <div className="flex justify-between text-sm">
                              <span className="text-gray-500">Type</span>
                              <span className="text-gray-300 font-medium">{details.is_direct ? 'Direct' : 'Indirect'}</span>
                            </div>
                            <div className="flex justify-between text-sm">
                              <span className="text-gray-500">Stops</span>
                              <span className="text-gray-300 font-medium">{details.stops}</span>
                            </div>
                          </>
                        )}

                        {mode === 'bus' && (
                           <div className="flex justify-between text-sm">
                            <span className="text-gray-500">Comfort</span>
                            <span className="text-gray-300 font-medium">{details.comfort_level}</span>
                          </div>
                        )}

                        {mode === 'private_transport' && (
                           <div className="flex justify-between text-sm">
                            <span className="text-gray-500">Type</span>
                            <span className="text-gray-300 font-medium">{details.type}</span>
                          </div>
                        )}
                      </div>

                      <div className="p-3 bg-white/5 rounded-xl mb-6">
                        <p className="text-xs text-gray-500 uppercase font-bold mb-1">Why recommended</p>
                        <p className="text-sm text-gray-300 leading-relaxed">{details.why_recommended}</p>
                      </div>

                      <div className="pt-4 border-t border-white/5">
                        <p className="text-[10px] text-gray-500 uppercase font-bold mb-3">Book on</p>
                        <div className="flex flex-wrap gap-2">
                          {mode === 'flight' && (<>
                            <a href={`https://www.makemytrip.com/flights/`} target="_blank" rel="noopener noreferrer" className="text-xs font-bold text-white bg-blue-600/80 hover:bg-blue-600 px-3 py-1.5 rounded-lg transition-colors">✈ MakeMyTrip</a>
                            <a href={`https://www.ixigo.com/flights`} target="_blank" rel="noopener noreferrer" className="text-xs font-bold text-white bg-orange-500/80 hover:bg-orange-500 px-3 py-1.5 rounded-lg transition-colors">✈ Ixigo</a>
                          </>)}
                          {mode === 'train' && (<>
                            <a href={`https://www.irctc.co.in/nget/train-search`} target="_blank" rel="noopener noreferrer" className="text-xs font-bold text-white bg-blue-700/80 hover:bg-blue-700 px-3 py-1.5 rounded-lg transition-colors">🚆 IRCTC</a>
                            <a href={`https://www.ixigo.com/trains`} target="_blank" rel="noopener noreferrer" className="text-xs font-bold text-white bg-orange-500/80 hover:bg-orange-500 px-3 py-1.5 rounded-lg transition-colors">🚆 Ixigo</a>
                            <a href={`https://www.makemytrip.com/railways/`} target="_blank" rel="noopener noreferrer" className="text-xs font-bold text-white bg-blue-600/80 hover:bg-blue-600 px-3 py-1.5 rounded-lg transition-colors">🚆 MMT</a>
                          </>)}
                          {mode === 'bus' && (<>
                            <a href={`https://www.redbus.in/`} target="_blank" rel="noopener noreferrer" className="text-xs font-bold text-white bg-red-600/80 hover:bg-red-600 px-3 py-1.5 rounded-lg transition-colors">🚌 RedBus</a>
                            <a href={`https://www.abhibus.com/`} target="_blank" rel="noopener noreferrer" className="text-xs font-bold text-white bg-green-600/80 hover:bg-green-600 px-3 py-1.5 rounded-lg transition-colors">🚌 AbhiBus</a>
                            <a href={`https://www.makemytrip.com/bus-tickets/`} target="_blank" rel="noopener noreferrer" className="text-xs font-bold text-white bg-blue-600/80 hover:bg-blue-600 px-3 py-1.5 rounded-lg transition-colors">🚌 MMT</a>
                          </>)}
                          {mode === 'private_transport' && (<>
                            <a href={`https://www.olacabs.com/`} target="_blank" rel="noopener noreferrer" className="text-xs font-bold text-white bg-yellow-600/80 hover:bg-yellow-600 px-3 py-1.5 rounded-lg transition-colors">🚗 Ola</a>
                            <a href={`https://www.uber.com/in/en/`} target="_blank" rel="noopener noreferrer" className="text-xs font-bold text-white bg-gray-700/80 hover:bg-gray-700 px-3 py-1.5 rounded-lg transition-colors">🚗 Uber</a>
                          </>)}
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
              <div className="mt-8 p-6 bg-gradient-to-br from-accent/10 to-accent-purple/10 rounded-2xl border border-accent/20">
                <div className="flex items-center gap-3 mb-3">
                  <Sparkles className="w-5 h-5 text-accent" />
                  <p className="text-sm text-accent font-bold uppercase tracking-wider">Agent's Recommendation</p>
                </div>
                <p className="text-gray-200 text-lg leading-relaxed">{plan.best_recommendation}</p>
              </div>
            </div>
          )}


          {activeTab === "food" && (
            <div className="space-y-6">
              <div className="glass-panel p-8">
                <h3 className="text-2xl font-bold mb-6 flex items-center gap-2">
                  <Coffee className="w-6 h-6 text-accent" /> Must-Try Local Cuisine
                </h3>
                <div className="flex flex-wrap gap-3">
                  {plan.food_plan?.must_try_dishes?.map((dish, i) => (
                    <span key={i} className="px-4 py-2 bg-accent/10 border border-accent/20 rounded-full text-accent font-bold">
                      {dish}
                    </span>
                  ))}
                </div>
              </div>
              <div className="glass-panel p-8">
                <h3 className="text-2xl font-bold mb-6">Top-Rated Food Spots</h3>
                <div className="grid md:grid-cols-2 gap-4">
                  {plan.food_plan?.famous_restaurants?.map((rest, i) => (
                    <div key={i} className="p-4 rounded-xl bg-white/5 border border-white/10 flex items-center justify-between gap-3">
                      <div className="flex items-center gap-3">
                        <div className="w-2 h-2 rounded-full bg-accent shrink-0" />
                        <span className="text-gray-300 font-medium">{rest}</span>
                      </div>
                      <div className="flex gap-2 shrink-0">
                        <a href={`https://www.zomato.com/search?q=${encodeURIComponent(rest)}`} target="_blank" rel="noopener noreferrer" className="text-[10px] font-bold text-white bg-red-500/80 hover:bg-red-500 px-2 py-1 rounded-md transition-colors">Zomato</a>
                        <a href={`https://www.swiggy.com/search?query=${encodeURIComponent(rest)}`} target="_blank" rel="noopener noreferrer" className="text-[10px] font-bold text-white bg-orange-500/80 hover:bg-orange-500 px-2 py-1 rounded-md transition-colors">Swiggy</a>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {activeTab === "tips" && (
            <div className="grid md:grid-cols-2 gap-6">
              <div className="glass-panel p-8">
                <h3 className="text-xl font-bold mb-6 flex items-center gap-2">
                  <Bookmark className="w-5 h-5 text-accent" /> Travel Tips
                </h3>
                <ul className="space-y-4 text-gray-400">
                  {plan.travel_tips?.map((tip, i) => (
                    <li key={i} className="flex gap-3">
                      <span className="text-accent">•</span> {tip}
                    </li>
                  ))}
                </ul>
              </div>
              <div className="space-y-6">
                <div className="glass-panel p-8">
                  <h3 className="text-xl font-bold mb-6 flex items-center gap-2">
                    <Heart className="w-5 h-5 text-red-400" /> Emergency Tips
                  </h3>
                  <ul className="space-y-4 text-gray-400">
                    {plan.emergency_tips?.map((tip, i) => (
                      <li key={i} className="flex gap-3 text-sm">
                        <span className="text-red-400 font-bold">!</span> {tip}
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="glass-panel p-8">
                  <h3 className="text-xl font-bold mb-6 flex items-center gap-2">
                    <Bookmark className="w-5 h-5 text-accent-purple" /> Packing List
                  </h3>
                  <ul className="space-y-2 text-gray-400 grid grid-cols-2">
                    {plan.packing_list?.map((item, i) => (
                      <li key={i} className="flex gap-3 text-sm">
                        <span className="text-accent-purple">•</span> {item}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Sidebar Widgets */}
        <div className="space-y-6">
          <div className="glass-panel p-6">
            <h4 className="text-lg font-bold mb-4 flex items-center gap-2">
              <MapIcon className="w-5 h-5 text-accent" /> Mini Map
            </h4>
            <div className="aspect-square rounded-xl bg-white/5 border border-white/10 overflow-hidden relative z-0 mb-4">
              {plan.destination_coords ? (
                <MapComponent itinerary={plan.itinerary} destinationCoords={plan.destination_coords} />
              ) : (
                <div className="w-full h-full flex items-center justify-center text-gray-500 text-sm">
                  Coordinates not available
                </div>
              )}
            </div>
            <button 
              onClick={() => window.open(`https://www.google.com/maps/search/${form.destination}+attractions`, "_blank")}
              className="w-full glass-btn-primary py-3"
            >
              Open in Google Maps
            </button>
          </div>

          <div className="glass-panel p-6">
            <h4 className="text-lg font-bold mb-4 flex items-center gap-2">
              <Train className="w-5 h-5 text-accent-purple" /> Booking Help
            </h4>
            <p className="text-sm text-gray-400 mb-6">{plan.best_recommendation}</p>


            <div className="grid grid-cols-2 gap-3">
              <button 
                onClick={() => window.open(plan.real_time_transport?.booking_links?.skyscanner || "https://www.skyscanner.co.in/", "_blank")} 
                className="glass-btn text-xs py-3 flex flex-col items-center gap-1"
              >
                <Plane className="w-4 h-4" /> Flights
              </button>
              <button 
                onClick={() => window.open(plan.real_time_transport?.booking_links?.makemytrip_hotels || "https://www.makemytrip.com/hotels/", "_blank")} 
                className="glass-btn text-xs py-3 flex flex-col items-center gap-1"
              >
                <Coffee className="w-4 h-4" /> Hotels
              </button>
              <button 
                onClick={() => window.open(plan.real_time_transport?.booking_links?.redbus || "https://www.redbus.in/", "_blank")} 
                className="glass-btn text-xs py-3 flex flex-col items-center gap-1"
              >
                <Sun className="w-4 h-4" /> RedBus
              </button>
              <button 
                onClick={() => window.open(plan.real_time_transport?.booking_links?.irctc || "https://www.irctc.co.in/", "_blank")} 
                className="glass-btn text-xs py-3 flex flex-col items-center gap-1"
              >
                <Train className="w-4 h-4" /> IRCTC
              </button>
            </div>
          </div>
        </div>
      </div>
      
      <ChatAssistant />
    </div>
  );
}

function StatCard({ icon, label, value }) {
  return (
    <div className="glass-panel p-6 flex items-center gap-4">
      <div className="p-3 bg-white/5 rounded-xl text-accent-purple">
        {icon}
      </div>
      <div>
        <p className="text-xs text-gray-500 uppercase tracking-wider font-bold mb-1">{label}</p>
        <p className="text-lg font-bold">{value}</p>
      </div>
    </div>
  );
}
